import dynamic from "next/dynamic";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Navigation from "@/components/Navigation";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import { MyApolloProvider } from "@/fassades";
import { AppProvider } from "@/contexts/AppContext";
const Cart = dynamic(() => import("@/components/Cart"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className={inter.className}>
                <MyApolloProvider>
                    <AppProvider>
                        <Navigation />
                        <Cart />
                        <div className="container mx-auto px-4">{children}</div>
                    </AppProvider>
                </MyApolloProvider>
            </body>
        </html>
    );
}
